### ISSUE TITLE
请问是否可以增加控制vps功能

### ISSUE THREAD

**Issue by wwb7700** [hongwenjun/mjj_home#1]
请问是否可以增加控制vps功能，例如重启，开机

**Comment by hongwenjun** [comment]
官方应该有API，我的代码也是朋友给我的

// case 'reboot':
// 	$result = post("reboot");

// 	if($result['error'] == 0) {
// 		$return = $result;
	
// 		$return['message'] = "Server rebooting now.";
// 	} else {
// 		$return = $result;
// 	}

// 	break;

//   a class="btn btn-default btn-block" href="?action=reboot" role="button">重启VPS</a>

MJJ的导航页: mjj_home 自己动手添加VPS重启和关机开机功能
https://262235.xyz/index.php/archives/687/
你可以试着自己修复
